### ISSUE TITLE
[IDEA] Add support for LiveLeak statistics

### ISSUE THREAD

**Issue by kjensenxz** [GeneralUnRest/neo8ball-irc#18]
Idea: Display LiveLeak statistics on a liveleak link being posted

**Comment by adedomin** [comment]
I don't get it.

**Comment by ineeee** [comment]
when u post a link the bot answers with some statistics:
```
<ine> http://youtu.be/OOFn0NiBMps
<neo8ball> Tokyo Ghoul   Unravel Lyrics Official Acoustic (3m48s) :: https://youtu.be/OOFn0NiBMps :: ▲ 12,805 :: ▼ 189 :: Views 657,878
```
the issue probably means it should do the same for liveleak videos

**Comment by adedomin** [comment]
too bad liveleak is now dead.

**Comment by ineeee** [comment]
u should do itemfix.com instead <sup>(who even uses that?)</sup>
