### ISSUE TITLE
Issue when reading titles with curly quotes (single and double)

### ISSUE THREAD

**Issue by Underdoge** [GeneralUnRest/neo8ball-irc#4]
Neo8ball will show â~@ and other symbols instead of curly quotes (single and double) when reading page titles.

**Comment by ghost** [comment]
ya the issue appears to be related to libxml used by xml2
it uses ISO Latin 1 character encoding and ignores locale.

upstream versions of xml2 fix this problem however old stable distros like debian and ubuntu still have xml2's with this problem.

hosted neo8ball on rizon will be fixed shortly, I'll probably download upstream xml2 and build it myself.

**Comment by ghost** [comment]
please note this is not a problem in neo8ball itself, xml2 or misconfiguration of locale. this is only an issue with the "officially" hosted neo8ball on rizon.

**Comment by Underdoge** [comment]
thanks man

**Comment by ghost** [comment]
weird i can't find upstream xml2....

the arch package works, I'll go pull the source package from arch and see if they use some kind of patchthat fixes this locale issue.

worst case I'll fix the debian source package myself

**Comment by ghost** [comment]
k gave up on html2, i was only using it to read out title tags anyhow
see: https://github.com/GeneralUnRest/neo8ball-irc/commit/a33f92522e2eadfb47315bd74f684ecf98ef1af4

example:
14:22 <+prussian> test: https://www.youtube.com/watch?v=cU8HrO7XuiE
14:22 <+neo8ball> ↑ Title :: MACINTOSH PLUS - リサフランク420 / 現代のコンピュー - YouTube

**Comment by Underdoge** [comment]
It works, thank you!
